# Generated by Django 4.2.4 on 2024-09-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rfid_card', models.BigIntegerField(unique=True)),
                ('job_description', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('added_to_machine', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
